- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Run docker container
      docker_container:
        name: hokku-birthday
        image: twobrowin/hokku-birthday:1.4.3
        state: started
        detach: yes
        restart: yes
        recreate: yes
        env:
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"
          SHEETS_NAME: 'Таблица для бота дней рождений в Пивном Петушке'
          SHEET_HBS: 'Дни рождения'
          SHEET_HBS_NAME: 'Род. падеж имени'
          SHEET_HBS_DATE: 'Дата рождения'
          SHEET_EMOJI: 'Emoji'
          SHEET_HOKKU: 'Строчки Хокку'
          SHEET_MAIN_TEXT: 'Основной текст'
          SHEET_MAIN_TEXT_CONDITION: 'Условие'
          SHEET_MAIN_TEXT_CONDITION_ONE: 'Одно ДР'
          SHEET_MAIN_TEXT_CONDITION_MANY: 'Несколько ДР'
          SHEET_MAIN_TEXT_TEXT: 'Текст'
          SHEET_TO_WHOM_SEND: 'Каналы для отправки'
          SHEET_TO_WHOM_SEND_ID: 'Telegram ID'
          CRON_TIME: '15 09 * * *'
    
