---
- name: Get secrets from vault
  hosts: all
  gather_facts: false
  roles:
    - role: bmstu.vats.init
      vault_path_inventory: bots/data/deploy,inventory-secrets.yaml
      vault_path_secrets:   bots/data/baumanec,hokku-birthday.yaml
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Run bot docker service
      docker_swarm_service:
        name: hokku-birthday
        image: twobrowin/hokku-birthday:2.0.1
        env:
          TZ: "Europe/Moscow"
          BOT_TOKEN:     "{{ secrets.bot_token }}"
          SHEETS_ACC:    "{{ secrets.sheet_acc | string }}"
          SHEETS_LINK:   "{{ secrets.sheets_link }}"