- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Run bot docker service
      docker_swarm_service:
        name: hokku-birthday
        image: twobrowin/hokku-birthday:1.4.5
        env:
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"
          SHEETS_NAME: 'Таблица для бота дней рождений в Пивном Петушке'
          SHEET_HBS: 'Дни рождения'
          SHEET_HBS_NAME: 'Род. падеж имени'
          SHEET_HBS_DATE: 'Дата рождения'
          SHEET_EMOJI: 'Emoji'
          SHEET_HOKKU: 'Строчки Хокку'
          SHEET_MAIN_TEXT: 'Основной текст'
          SHEET_MAIN_TEXT_CONDITION: 'Условие'
          SHEET_MAIN_TEXT_CONDITION_ONE: 'Одно ДР'
          SHEET_MAIN_TEXT_CONDITION_MANY: 'Несколько ДР'
          SHEET_MAIN_TEXT_TEXT: 'Текст'
          SHEET_TO_WHOM_SEND: 'Каналы для отправки'
          SHEET_TO_WHOM_SEND_ID: 'Telegram ID'
          CRON_TIME: '15 09 * * *'