container:
  image: twobrowin/hokku-birthday:2.2.4-rc.0
  imagePullPolicy: IfNotPresent

  env:
  - name: TZ
    value: Europe/Moscow
  - name: BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: hokku-birthday
        key: bot_token
  - name: SHEETS_ACC
    valueFrom:
      secretKeyRef:
        name: hokku-birthday
        key: sheet_acc
  - name: SHEETS_LINK
    valueFrom:
      secretKeyRef:
        name: hokku-birthday
        key: sheets_link
  
  resources:
    requests:
      cpu: 150m
      memory: 150M
    limits:
      cpu: 200m
      memory: 200M